---
name: Build and Push Container with Podman

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FEDORA_VERSION: 42
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      IMAGE_TAGS: latest, ${{ github.sha }}
      IMAGE_REGISTRY: ghcr.io
      IMAGE_REPOSITORY: ${{ github.event.repository.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch
        uses: docker/setup-qemu-action@v3

      - name: Build and push image 
        id: build-push-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          platforms: amd64, arm64
          build-args: |
            FEDORA_VERSION=${{ env.FEDORA_VERSION }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
          dockerfiles: ./Containerfile
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.build-push-image.outputs.registry-paths }}"
