---
name: Build and Push Container with Podman

on:
  push:
    branches:
      - main
  workflow_dispatch:

 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      FEDORA_VERSION: 42
      BUILD_DATE: ${{ github.event.head_commit.timestamp }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch
        uses: docker/setup-qemu-action@v3

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt -y install podman

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin


      - name: Build multi-arch image with Podman
        env:
          TAG_LATEST: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          TAG_SHA: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7}
        run: |
          podman buildx --platform linux/amd64,linux/arm64 \
            --build-arg "$FEDORA_VERSION" \
            --build-arg BUILD_DATE="$BUILD_DATE" \
            --build-arg VCS_REF="${GITHUB_SHA::7}·" \
            --tag "$TAG_LATEST" \
            --tag "$TAG_SHA" \
            --file Containerfile . \
            --push
